name: venv
channels:
  - conda-forge
  - pytorch

dependencies:
  - python==3.7
  - pytorch==1.2.0
  - opencv==4.1.2
  - matplotlib==3.1.1
  - pandas==1.0.3
  - pip:
    - git+https://github.com/kornia/kornia.git
    - git+https://github.com/ElementAI/haven
